-- Seed file for basic testing
-- Run this after all migrations are complete

-- Clear existing data
DELETE FROM games CASCADE;
DELETE FROM players CASCADE;
DELETE FROM player_cards CASCADE;
DELETE FROM cards CASCADE;
DELETE FROM decks CASCADE;
DELETE FROM users CASCADE;


-- Reset ID sequences
ALTER SEQUENCE games_id_seq RESTART WITH 1;
ALTER SEQUENCE players_id_seq RESTART WITH 1;
ALTER SEQUENCE player_cards_id_seq RESTART WITH 1;
ALTER SEQUENCE cards_id_seq RESTART WITH 1;
ALTER SEQUENCE decks_id_seq RESTART WITH 1;
ALTER SEQUENCE users_id_seq RESTART WITH 1;

-- Insert users
INSERT into users (username, email, birthday, auth0_id)
VALUES
('robouser1', 'robouser1@gmail.com', '2000-01-01', 'auth0|6852f3ed03ace7188c8886a2'),
('robouser2', 'robouser2@yahoo.com', '2000-01-01', 'auth0|6852f3af03ace7188c888682'),  -- password = Password123!
('testuser', 'testuser@tester.com', '2000-01-01', 'auth0|6852b1d99e1842d8a9fc6bb1');        -- pass = NAHs0n!!

-- Insert decks
INSERT INTO decks (name, unique_stat_name, thumbnail)
VALUES
('The Simpsons', 'D''oh! Factor', '/deckImages/simpsons/thumbnail.jpg'),
('Harry Potter', 'Spellcasting', '/deckImages/harryPotter/thumbnail.jpg'),
('Marvel', 'Superpower', '/deckImages/marvel/thumbnail.jpg'),
('Disney', 'Disney Magic', '/deckImages/disney/thumbnail.jpg'),
('Pop-culture', 'Memeability', '/deckImages/popculture/thumbnail.jpg'),
('Brit-tv', 'Cuppa Strength', '/deckImages/brittv/thumbnail.jpg'),
('Kids-tv', 'Giggle Power', '/deckImages/kidstv/thumbnail.jpg');

-- Insert cards
INSERT INTO cards
(deck_id, name, strength, wisdom, defence, unique_stat, luck, flavour_text, image)
VALUES
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Homer Simpson', 67, 31, 52, 93, 42, 'Loves donuts. Frequently causes his own disasters.', '/deckImages/simpsons/homer.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Marge Simpson', 51, 72, 66, 22, 62, 'The patient glue holding the family together.', '/deckImages/simpsons/marge.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Bart Simpson', 43, 46, 36, 82, 74, 'Eat my shorts!', '/deckImages/simpsons/bart.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Lisa Simpson', 32, 96, 41, 11, 72, 'A saxophone-playing genius in a world of chaos.', '/deckImages/simpsons/lisa.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Maggie Simpson', 11, 82, 22, 4, 87, 'Silent, but somehow still saves the day.', '/deckImages/simpsons/maggie.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Ned Flanders', 44, 77, 59, 6, 64, 'Hi-diddly-ho, neighborino!', '/deckImages/simpsons/ned.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Mr. Burns', 21, 83, 24, 49, 14, 'Excellent... but weak.', '/deckImages/simpsons/burns.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Waylon Smithers', 36, 74, 44, 17, 38, 'Burns’ loyal assistant. Has all his shots.', '/deckImages/simpsons/smithers.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Milhouse Van Houten', 27, 51, 32, 58, 33, 'Everything’s coming up Milhouse!', '/deckImages/simpsons/milhouse.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Nelson Muntz', 67, 36, 53, 69, 31, 'Ha-ha!', '/deckImages/simpsons/nelson.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Ralph Wiggum', 13, 22, 22, 98, 91, 'I choo-choo-choose chaos.', '/deckImages/simpsons/ralph.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Chief Wiggum', 52, 36, 44, 73, 52, 'The law is optional.', '/deckImages/simpsons/wiggum.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Apu Nahasapeemapetilon', 44, 87, 42, 29, 72, 'Thank you, come again!', '/deckImages/simpsons/apu.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Comic Book Guy', 27, 89, 34, 41, 27, 'Worst. Stat block. Ever.', '/deckImages/simpsons/comic_book_guy.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Moe Szyslak', 53, 41, 56, 59, 43, 'Owner of the saddest bar in town.', '/deckImages/simpsons/moe.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Barney Gumble', 72, 21, 51, 91, 32, 'Burp-powered powerhouse.', '/deckImages/simpsons/barney.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Krusty the Clown', 31, 48, 34, 87, 66, 'Funny, in a depressing kind of way.', '/deckImages/simpsons/krusty.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Sideshow Bob', 42, 96, 49, 21, 44, 'Revenge is an art form.', '/deckImages/simpsons/sideshow_bob.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Principal Skinner', 39, 74, 56, 26, 49, 'Steamed hams specialist.', '/deckImages/simpsons/skinner.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Edna Krabappel', 32, 81, 46, 37, 57, 'Don’t test her patience.', '/deckImages/simpsons/edna.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Groundskeeper Willie', 81, 49, 74, 46, 36, 'Angry, shirtless, and proud.', '/deckImages/simpsons/willie.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Lenny Leonard', 46, 48, 41, 58, 48, 'Carl’s other half.', '/deckImages/simpsons/lenny.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Carl Carlson', 52, 57, 46, 57, 53, 'The voice of reason at the plant.', '/deckImages/simpsons/carl.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Itchy', 92, 28, 33, 84, 49, 'Tiny, violent mouse.', '/deckImages/simpsons/itchy.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Scratchy', 84, 26, 29, 94, 46, 'Unlucky cartoon cat.', '/deckImages/simpsons/scratchy.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Patty Bouvier', 36, 67, 38, 19, 29, 'Chain-smoking cynic.', '/deckImages/simpsons/patty.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Selma Bouvier', 34, 59, 42, 23, 28, 'Also a chain-smoking cynic.', '/deckImages/simpsons/selma.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Reverend Lovejoy', 29, 71, 44, 13, 48, 'Spiritually checked out.', '/deckImages/simpsons/lovejoy.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Snake Jailbird', 61, 42, 47, 74, 33, 'Yesss, crime is cool.', '/deckImages/simpsons/snake.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Dr. Nick Riviera', 26, 33, 18, 87, 27, 'Hi everybody!', '/deckImages/simpsons/dr_nick.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Kent Brockman', 31, 76, 29, 19, 38, 'I, for one, welcome our new insect overlords.', '/deckImages/simpsons/kent.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Troy McClure', 41, 54, 31, 63, 51, 'You might remember him from such cards as this one.', '/deckImages/simpsons/troy.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Hans Moleman', 6, 38, 11, 97, 16, 'Moleman in the Morning is canceled.', '/deckImages/simpsons/moleman.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Bumblebee Man', 33, 29, 36, 79, 56, '¡Ay, caramba!', '/deckImages/simpsons/bumblebee.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Fat Tony', 67, 62, 55, 33, 41, 'The godfather of Springfield crime.', '/deckImages/simpsons/fat_tony.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Harry Potter', 77, 71, 67, 89, 82, 'The Boy Who Lived. And Lived. And Lived.', '/deckImages/harryPotter/harry.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Hermione Granger', 42, 98, 54, 96, 63, 'Probably read this card before you did.', '/deckImages/harryPotter/hermione.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Ron Weasley', 61, 67, 62, 68, 76, 'Loyal sidekick. Accident-prone, charmingly so.', '/deckImages/harryPotter/ron.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Albus Dumbledore', 43, 98, 87, 98, 71, 'More titles than a fantasy novel.', '/deckImages/harryPotter/dumbledore.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Lord Voldemort', 86, 90, 76, 97, 22, 'He Who Must Not Be Underestimated.', '/deckImages/harryPotter/voldemort.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Severus Snape', 51, 95, 71, 91, 48, 'Always.', '/deckImages/harryPotter/snape.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Draco Malfoy', 46, 59, 41, 64, 51, 'Talks big. Often runs away.', '/deckImages/harryPotter/draco.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Minerva McGonagall', 56, 91, 86, 94, 52, 'Strict, brilliant, occasionally turns into a cat.', '/deckImages/harryPotter/mcgonagall.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Rubeus Hagrid', 91, 46, 72, 34, 66, 'Larger than life. And magical creatures.', '/deckImages/harryPotter/hagrid.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Sirius Black', 71, 71, 66, 81, 61, 'Loyal, brave, tragically misunderstood.', '/deckImages/harryPotter/sirius.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Remus Lupin', 66, 84, 69, 86, 57, 'Werewolf with wisdom and a heart.', '/deckImages/harryPotter/lupin.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Bellatrix Lestrange', 71, 74, 61, 94, 42, 'Mad, bad, and magically dangerous.', '/deckImages/harryPotter/bellatrix.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Luna Lovegood', 36, 81, 47, 74, 92, 'Exceptionally odd, exceptionally gifted.', '/deckImages/harryPotter/luna.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Neville Longbottom', 61, 71, 81, 69, 66, 'The unlikeliest hero. Until he isn’t.', '/deckImages/harryPotter/neville.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Ginny Weasley', 66, 71, 61, 81, 71, 'Quiet strength, blazing Bat-Bogey Hexes.', '/deckImages/harryPotter/ginny.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Fred Weasley', 51, 66, 56, 61, 87, 'Half of a prank legend.', '/deckImages/harryPotter/fred.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'George Weasley', 52, 64, 57, 59, 88, 'Other half of a prank legend.', '/deckImages/harryPotter/george.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Molly Weasley', 67, 74, 71, 68, 56, 'Do not cross this mum.', '/deckImages/harryPotter/molly.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Arthur Weasley', 42, 71, 62, 66, 63, 'Fascinated by Muggle plugs.', '/deckImages/harryPotter/arthur.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Fleur Delacour', 61, 74, 61, 76, 71, 'Beauxbatons’ best, with Veela flair.', '/deckImages/harryPotter/fleur.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Cedric Diggory', 71, 74, 71, 69, 67, 'The goodest boy in Hogwarts.', '/deckImages/harryPotter/cedric.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Cho Chang', 46, 71, 51, 66, 72, 'Seeker of hearts and snitches.', '/deckImages/harryPotter/cho.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Lucius Malfoy', 56, 81, 61, 72, 42, 'Fancy cane, shady morals.', '/deckImages/harryPotter/lucius.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Nymphadora Tonks', 56, 74, 61, 74, 81, 'Don’t call her Nymphadora.', '/deckImages/harryPotter/tonks.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Kingsley Shacklebolt', 66, 84, 76, 86, 62, 'Cool under pressure. And with spells.', '/deckImages/harryPotter/kingsley.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Dolores Umbridge', 22, 69, 46, 59, 22, 'Pink, perky, and pure evil.', '/deckImages/harryPotter/umbridge.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Horace Slughorn', 42, 79, 56, 69, 67, 'Knows everyone, and their potions.', '/deckImages/harryPotter/slughorn.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Gilderoy Lockhart', 22, 59, 31, 27, 92, 'Author, fraud, legend in his own mind.', '/deckImages/harryPotter/lockhart.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Alastor Moody', 81, 71, 92, 84, 46, 'Constant vigilance!', '/deckImages/harryPotter/moody.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Peter Pettigrew', 31, 51, 41, 56, 27, 'Wormtail: rat in every sense.', '/deckImages/harryPotter/pettigrew.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Spider-Man', 61, 86, 52, 94, 72, 'Agile web-slinger with a sixth sense for danger.', '/deckImages/marvel/spiderman.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Iron Man', 72, 96, 58, 84, 52, 'Genius inventor in a high-tech suit of armor.', '/deckImages/marvel/ironman.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Thor', 94, 82, 91, 99, 61, 'God of Thunder wielding Mjolnir.', '/deckImages/marvel/thor.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Hulk', 94, 44, 86, 84, 37, 'The madder he gets, the stronger he gets.', '/deckImages/marvel/hulk.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Captain America', 86, 71, 79, 62, 76, 'Super soldier with an indestructible shield.', '/deckImages/marvel/captainamerica.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Black Widow', 67, 81, 72, 49, 87, 'Master spy and hand-to-hand combatant.', '/deckImages/marvel/blackwidow.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Doctor Strange', 51, 99, 61, 96, 41, 'Sorcerer Supreme with mystical abilities.', '/deckImages/marvel/doctorstrange.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Black Panther', 91, 86, 84, 76, 67, 'King of Wakanda with enhanced abilities.', '/deckImages/marvel/blackpanther.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Ant‑Man', 49, 76, 62, 66, 82, 'Can shrink to the size of an ant with increased strength.', '/deckImages/marvel/antman.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Wolverine', 96, 61, 86, 89, 56, 'Regenerative healing factor and adamantium claws.', '/deckImages/marvel/wolverine.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Scarlet Witch', 72, 96, 73, 98, 66, 'Reality-warping powers and chaos magic.', '/deckImages/marvel/scarletwitch.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Vision', 87, 91, 82, 79, 62, 'Android with the Mind Stone and density control.', '/deckImages/marvel/vision.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Falcon', 74, 72, 67, 62, 87, 'Skilled pilot and hand-to-hand combatant.', '/deckImages/marvel/falcon.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Hawkeye', 69, 79, 66, 54, 92, 'Master archer with impeccable aim.', '/deckImages/marvel/hawkeye.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Star‑Lord', 66, 77, 69, 59, 81, 'Leader of the Guardians with a quick wit.', '/deckImages/marvel/starlord.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Gamora', 86, 71, 74, 66, 76, 'Deadliest woman in the universe.', '/deckImages/marvel/gamora.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Drax', 94, 51, 91, 79, 52, 'Driven by vengeance and unmatched strength.', '/deckImages/marvel/drax.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Rocket Raccoon', 61, 82, 57, 68, 86, 'Weapons expert with a sharp tongue.', '/deckImages/marvel/rocketraccoon.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Groot', 99, 41, 96, 84, 62, 'Tree-like being with regenerative abilities.', '/deckImages/marvel/groot.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Deadpool', 86, 71, 61, 89, 96, 'Regenerative healing and a twisted sense of humor.', '/deckImages/marvel/deadpool.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Thanos', 99, 84, 92, 98, 52, 'Mad Titan with the power of the Infinity Stones.', '/deckImages/marvel/thanos.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Loki', 71, 91, 64, 86, 76, 'God of Mischief with illusionary powers.', '/deckImages/marvel/loki.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Venom', 91, 81, 76, 89, 66, 'Alien symbiote with enhanced strength.', '/deckImages/marvel/venom.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Magneto', 81, 96, 71, 99, 62, 'Master of magnetism and metal manipulation.', '/deckImages/marvel/magneto.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Storm', 74, 91, 71, 96, 66, 'Weather-controlling mutant with flight capabilities.', '/deckImages/marvel/storm.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Rogue', 86, 76, 81, 89, 71, 'Absorbs powers and memories through touch.', '/deckImages/marvel/rogue.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Professor X', 71, 99, 61, 94, 53, 'Telepathic leader of the X‑Men.', '/deckImages/marvel/professorx.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Jean Grey', 81, 96, 71, 89, 61, 'Telekinetic and telepathic mutant.', '/deckImages/marvel/jeangrey.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Cyclops', 86, 81, 76, 84, 66, 'Optic blast-wielding leader of the X‑Men.', '/deckImages/marvel/cyclops.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Silver Surfer', 81, 91, 81, 99, 56, 'Cosmic-powered herald who soars the spaceways.', '/deckImages/marvel/silversurfer.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Mickey Mouse', 39, 79, 43, 96, 86, 'The face of Disney — cheerful and full of wonder.', '/deckImages/disney/mickey.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Minnie Mouse', 37, 77, 47, 84, 92, 'Graceful, loving, and always in style.', '/deckImages/disney/minnie.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Donald Duck', 48, 66, 53, 63, 72, 'Short temper, big heart, and even bigger voice.', '/deckImages/disney/donald.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Goofy', 61, 54, 61, 49, 94, 'Clumsy, lucky, and full of surprises.', '/deckImages/disney/goofy.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Elsa', 71, 79, 73, 98, 61, 'Queen of ice and empowerment.', '/deckImages/disney/elsa.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Anna', 62, 69, 67, 76, 87, 'Brave, loyal, and full of warmth.', '/deckImages/disney/anna.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Olaf', 34, 62, 44, 68, 97, 'Loves warm hugs and summer.', '/deckImages/disney/olaf.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Simba', 78, 71, 77, 64, 72, 'King in the making with a mighty roar.', '/deckImages/disney/simba.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Mufasa', 89, 86, 88, 81, 59, 'The wise and noble king of the Pride Lands.', '/deckImages/disney/mufasa.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Scar', 66, 87, 57, 74, 41, 'Cunning, theatrical, and full of betrayal.', '/deckImages/disney/scar.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Ariel', 49, 69, 61, 88, 76, 'Curious mermaid with a voice of magic.', '/deckImages/disney/ariel.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Ursula', 61, 81, 66, 94, 51, 'Sea witch with serious flair.', '/deckImages/disney/ursula.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Aladdin', 68, 76, 66, 86, 82, 'Street-smart prince with a magic carpet.', '/deckImages/disney/aladdin.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Genie', 82, 83, 71, 97, 69, 'Phenomenal cosmic powers, itty-bitty living space.', '/deckImages/disney/genie.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Jasmine', 59, 79, 62, 74, 90, 'Royal rebel with a strong will.', '/deckImages/disney/jasmine.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Moana', 78, 76, 77, 78, 72, 'Wayfinder, ocean whisperer, and heart of Te Fiti.', '/deckImages/disney/moana.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Maui', 96, 61, 81, 84, 56, 'Demigod of the wind and sea. You’re welcome.', '/deckImages/disney/maui.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Tiana', 69, 86, 69, 71, 64, 'Hard-working dreamer turned princess.', '/deckImages/disney/tiana.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Rapunzel', 57, 86, 62, 92, 81, 'Hair for days. Hope for miles.', '/deckImages/disney/rapunzel.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Flynn Rider', 64, 69, 61, 59, 88, 'Smolder level: expert.', '/deckImages/disney/flynn.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Cinderella', 38, 74, 52, 86, 96, 'Proof that shoes can change your life.', '/deckImages/disney/cinderella.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Belle', 44, 89, 57, 79, 78, 'Brains, books, and beauty.', '/deckImages/disney/belle.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Beast', 89, 69, 86, 69, 64, 'Big and brooding, with a tender heart.', '/deckImages/disney/beast.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Maleficent', 69, 90, 74, 97, 56, 'Mistress of all evil, and it shows.', '/deckImages/disney/maleficent.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Peter Pan', 56, 69, 57, 82, 96, 'Never grows up — also flies.', '/deckImages/disney/peterpan.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Tinker Bell', 34, 64, 42, 87, 92, 'Small, sparkly, and sassy.', '/deckImages/disney/tinkerbell.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Hercules', 96, 62, 86, 74, 71, 'Zero to hero real quick.', '/deckImages/disney/hercules.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Stitch', 86, 52, 77, 69, 86, 'Cute and chaotic. Mostly chaotic.', '/deckImages/disney/stitch.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Pocahontas', 71, 79, 69, 74, 82, 'Speaks to nature. Runs like the wind.', '/deckImages/disney/pocahontas.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Mulan', 86, 86, 79, 72, 76, 'Saved China. Disguised as a man. NBD.', '/deckImages/disney/mulan.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Walter White', 66, 94, 71, 84, 56, 'Heisenberg always cooks up a plan.', '/deckImages/popculture/walter_white.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Tony Soprano', 79, 76, 82, 68, 59, 'Family first, with a side of chaos.', '/deckImages/popculture/tony_soprano.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Dexter Morgan', 61, 81, 63, 74, 62, 'Killer by night, forensic genius by day.', '/deckImages/popculture/dexter_morgan.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Rick Grimes', 74, 66, 78, 62, 61, 'Survivor in a world gone mad.', '/deckImages/popculture/rick_grimes.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Joe Exotic', 43, 37, 46, 97, 88, 'Zookeeper gone wild, meme legend.', '/deckImages/popculture/joe_exotic.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Tommy Shelby', 71, 84, 72, 61, 66, 'Sharp dresser, sharper mind.', '/deckImages/popculture/tommy_shelby.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Villanelle', 67, 76, 61, 74, 69, 'Deadly, stylish, and unpredictable.', '/deckImages/popculture/villanelle.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Joe Goldberg', 52, 72, 57, 69, 71, 'Charming but creepy book lover.', '/deckImages/popculture/joe_goldberg.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Jon Snow', 84, 72, 86, 61, 54, 'Knows nothing, but fights everything.', '/deckImages/popculture/jon_snow.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Daenerys Targaryen', 88, 71, 77, 74, 52, 'Mother of Dragons and drama.', '/deckImages/popculture/daenerys.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Eleven', 69, 81, 62, 86, 59, 'Powered by waffles and psychic vibes.', '/deckImages/popculture/eleven.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'The Mandalorian', 76, 69, 91, 61, 54, 'This is the way.', '/deckImages/popculture/mandalorian.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Grogu', 27, 62, 38, 99, 94, 'Cutest force-user in the galaxy.', '/deckImages/popculture/grogu.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Joel', 81, 76, 82, 61, 57, 'Survivor with a heart of stone.', '/deckImages/popculture/joel.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Geralt of Rivia', 91, 72, 84, 67, 56, 'Witcher with a silver tongue.', '/deckImages/popculture/geralt.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Professor', 41, 96, 51, 76, 63, 'Mastermind with a plan for every plan.', '/deckImages/popculture/professor.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Michael Scott', 34, 52, 39, 98, 92, 'World’s best boss in his own mind.', '/deckImages/popculture/michael_scott.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Dwight Schrute', 54, 66, 59, 94, 87, 'Beet farmer and assistant to the regional boss.', '/deckImages/popculture/dwight_schrute.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Ron Burgundy', 47, 63, 51, 91, 84, 'Stay classy, San Diego.', '/deckImages/popculture/ron_burgundy.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Sheldon Cooper', 32, 94, 43, 89, 76, 'Bazinga! Genius with a social defect.', '/deckImages/popculture/sheldon_cooper.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Eric Cartman', 44, 54, 49, 97, 93, 'Respect my authoritah!', '/deckImages/popculture/eric_cartman.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'SpongeBob SquarePants', 37, 69, 44, 94, 98, 'Absorbent and yellow and porous is he.', '/deckImages/popculture/spongebob.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Stewie Griffin', 48, 84, 42, 92, 79, 'Evil baby with big plans.', '/deckImages/popculture/stewie_griffin.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Rick Sanchez', 57, 99, 58, 96, 67, 'Wubba lubba dub dub!', '/deckImages/popculture/rick_sanchez.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'John Wick', 99, 67, 94, 74, 41, 'Baba Yaga on a mission.', '/deckImages/popculture/john_wick.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Barbie', 61, 71, 58, 91, 84, 'Life in plastic, it’s fantastic.', '/deckImages/popculture/barbie.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Ken', 58, 62, 54, 97, 88, 'Ken-doll with a modern twist.', '/deckImages/popculture/ken.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Joker', 66, 79, 62, 86, 49, 'Put on a happy face... or don’t.', '/deckImages/popculture/joker.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Homelander', 97, 67, 88, 69, 43, 'The hero everyone fears.', '/deckImages/popculture/homelander.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Invincible', 91, 63, 91, 62, 51, 'Not your average superhero.', '/deckImages/popculture/invincible.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Chandler Bing', 43, 62, 47, 95, 58, 'Could he *be* any more sarcastic?', '/deckImages/popculture/chandler.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Darth Vader', 93, 88, 81, 72, 49, 'Once Anakin, now asthma with a lightsaber.', '/deckImages/popculture/vader.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Frodo Baggins', 29, 76, 54, 61, 77, 'Tiny hobbit, massive burden. Loves rings.', '/deckImages/popculture/frodo.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Godzilla', 99, 34, 91, 84, 25, 'Tokyo''s worst tourist. Loud, lizard, legend.', '/deckImages/popculture/godzilla.jpg'),
((SELECT id FROM decks WHERE name = 'Pop-culture'), 'Hannibal Lecter', 56, 98, 67, 52, 41, 'Brilliant. Cultured. Really into... fine dining.', '/deckImages/popculture/hannibal.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Phil Mitchell', 85, 55, 80, 92, 38, 'East End tough, heart of gold… occasionally.', '/deckImages/brittv/phil_mitchell.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Del Boy', 60, 70, 50, 78, 90, 'He’ll have that framed and gutted, Rodney.', '/deckImages/brittv/del_boy.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Mr Bean', 40, 30, 30, 85, 99, 'Silent legend of slapstick and Minis.', '/deckImages/brittv/mr_bean.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Dot Cotton', 30, 65, 40, 72, 45, 'Grab a fag, grab some gossip, bless.', '/deckImages/brittv/dot_cotton.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Davina McCall', 50, 60, 55, 68, 75, 'Reality host with boundless enthusiasm.', '/deckImages/brittv/davina_mccall.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Dermot O’Leary', 52, 63, 57, 65, 70, 'Chilled charm with a ﬂair for talent shows.', '/deckImages/brittv/dermot_oleary.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Ant McPartlin', 55, 60, 58, 70, 83, 'The ever‑smiling half of Britain’s fave duo.', '/deckImages/brittv/ant_mcpartlin.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Dec Donnelly', 55, 60, 58, 70, 83, 'Steadying presence next to Ant’s sparkle.', '/deckImages/brittv/dec_donnelly.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Claudia Winkleman', 50, 68, 56, 66, 78, 'Quirky, candles, backstage brilliance.', '/deckImages/brittv/claudia_winkleman.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Graham Norton', 58, 75, 60, 70, 88, 'Red sofa king with razor-sharp wit.', '/deckImages/brittv/graham_norton.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'David Brent', 45, 40, 45, 55, 95, 'Boss with cringe dreams and big illusions.', '/deckImages/brittv/david_brent.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Alan Partridge',  50, 55, 50, 60, 90, 'Radio awkwardness meets midlands charm.', '/deckImages/brittv/alan_partridge.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Doctor Who', 70, 90, 65, 88, 80, 'Time‑travelling hero with sonic panache.', '/deckImages/brittv/doctor_who.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'David Attenborough', 30, 99, 40, 75, 65, 'The soothing voice of the natural world.', '/deckImages/brittv/david_attenborough.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Bruce Forsyth', 40, 65, 50, 70, 85, 'Nice to see you, to see you… nice.', '/deckImages/brittv/bruce_forsyth.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Luther', 85, 60, 80, 68, 55, 'Brooding detective with chemistry… and teeth.', '/deckImages/brittv/luther.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Jeremy Paxman', 40, 95, 45, 60, 50, 'The interrogator‑in‑chief of British TV.', '/deckImages/brittv/jeremy_paxman.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Louis Theroux', 30, 92, 45, 72, 60, 'Warm‑hearted docu‑explorer with curiosity.', '/deckImages/brittv/louis_theroux.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'David Beckham', 75, 60, 70, 65, 85, 'Golden‑boot legend turned TV celeb.', '/deckImages/brittv/david_beckham.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Jeremy Clarkson', 70, 55, 65, 62, 80, 'Love‑him‑or‑loathe‑him motoring maestro.', '/deckImages/brittv/jeremy_clarkson.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Piers Morgan', 60, 50, 60, 58, 55, 'Controversial host with strong opinions.', '/deckImages/brittv/piers_morgan.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Simon Cowell', 55, 60, 58, 70, 68, 'Judgmental magnate of X Factor fame.', '/deckImages/brittv/simon_cowell.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Carol Vorderman', 50, 85, 55, 68, 75, 'Maths whizz with numbers and charm.', '/deckImages/brittv/carol_vorderman.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Ben Shephard', 50, 60, 55, 65, 72, 'Breakfast TV staple with cheeky grin.', '/deckImages/brittv/ben_shephard.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Paul Hollywood', 65, 70, 60, 68, 70, 'The bread judge with steely stare and handshake.', '/deckImages/brittv/paul_hollywood.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Noel Edmonds', 48, 60, 55, 66, 80, 'Party‑host with a playful grin and puzzles.', '/deckImages/brittv/noel_edmonds.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Anne Robinson', 48, 70, 55, 60, 65, 'The harsh quizmistress with biting put‑downs.', '/deckImages/brittv/anne_robinson.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Martin Freeman', 60, 65, 58, 66, 82, 'Lovable everyman with impeccable timing.', '/deckImages/brittv/martin_freeman.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Judi Dench', 55, 90, 60, 70, 88, 'Legendary actress with gravitas galore.', '/deckImages/brittv/judi_dench.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Alan Carr', 50, 70, 55, 68, 90, 'Chatty comedian with infectious energy.', '/deckImages/brittv/alan_carr.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Lenny Henry', 55, 70, 55, 68, 85, 'Comedic force and Variety legend.', '/deckImages/brittv/lenny_henry.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Jay Cartwright', 65, 55, 60, 70, 77, 'Shameless’ cheeky Scouser with heart.', '/deckImages/brittv/jay_cartwright.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'James Acaster', 45, 80, 50, 68, 92, 'Off‑kilter comedian with surreal charm.', '/deckImages/brittv/james_acaster.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Greg Davies', 65, 70, 60, 72, 88, 'Tall comic with booming voice and presence.', '/deckImages/brittv/greg_davies.jpg'),
((SELECT id FROM decks WHERE name = 'Brit-tv'), 'Peter Kay', 55, 75, 58, 70, 95, 'Everyday observational humour with warmth.', '/deckImages/brittv/peter_kay.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Teletubbies', 32, 38, 41, 91, 64, 'Lovable, bouncy, and endlessly surreal.', '/deckImages/kidstv/teletubbies.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Duggee', 77, 72, 68, 85, 56, 'Leader of The Squirrel Club. Much wow, many badges.', '/deckImages/kidstv/duggee.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Bluey', 58, 61, 54, 94, 73, 'A blue heeler pup with endless imagination.', '/deckImages/kidstv/bluey.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Ms. Rachel', 41, 91, 53, 74, 65, 'Bringing learning and love through song.', '/deckImages/kidstv/ms_rachel.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Peppa Pig', 50, 59, 44, 83, 68, 'Snort! It’s Peppa, the sassy piglet.', '/deckImages/kidstv/peppa.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Postman Pat', 46, 71, 63, 52, 74, 'With his black and white cat, always on time.', '/deckImages/kidstv/postman_pat.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Dora', 53, 66, 47, 76, 69, 'Explorer, adventurer, backpack-tamer.', '/deckImages/kidstv/dora.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Elmo', 39, 57, 42, 97, 86, 'Red, fuzzy, giggly, and loved by millions.', '/deckImages/kidstv/elmo.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Arthur Read', 47, 74, 61, 63, 58, 'An aardvark who makes growing up a bit easier.', '/deckImages/kidstv/arthur.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Bob the Builder', 76, 68, 79, 62, 54, 'Can he fix it? Yes, he can!', '/deckImages/kidstv/bob.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Chase', 66, 58, 71, 68, 61, 'A brave pup always on the case.', '/deckImages/kidstv/chase.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Thomas', 61, 60, 72, 59, 65, 'A cheeky little engine with a big heart.', '/deckImages/kidstv/thomas.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Fireman Sam', 73, 66, 76, 57, 60, 'Saving Pontypandy one emergency at a time.', '/deckImages/kidstv/fireman_sam.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Noddy', 44, 54, 48, 65, 62, 'The little wooden toy with a bell on his hat.', '/deckImages/kidstv/noddy.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Charlie and Lola', 35, 69, 38, 81, 67, 'Sibling charm and quirky British humour.', '/deckImages/kidstv/charlie_lola.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Paddington Bear', 52, 78, 60, 58, 72, 'Manners, marmalade, and heartwarming mischief.', '/deckImages/kidstv/paddington.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Iggle Piggle', 31, 36, 42, 87, 71, 'Blanket in hand, boat at the ready.', '/deckImages/kidstv/iggle_piggle.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Mr Tumble', 43, 64, 51, 93, 69, 'Spotty bag, signing hands, big heart.', '/deckImages/kidstv/mr_tumble.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Mr Blobby', 82, 24, 55, 99, 58, 'Utter chaos in a pink and yellow blob.', '/deckImages/kidstv/mr_blobby.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Scooby Doo', 66, 53, 57, 75, 77, 'Hungry, cowardly, but always lovable.', '/deckImages/kidstv/scooby.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Baby Shark', 45, 37, 39, 88, 83, 'Doo doo doo doo doo doo!', '/deckImages/kidstv/baby_shark.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Barney the Dinosaur', 54, 63, 66, 78, 59, 'A big purple dinosaur who loves you.', '/deckImages/kidstv/barney.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Pingu', 40, 42, 50, 92, 66, 'Noot noot!', '/deckImages/kidstv/pingu.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Supertato', 63, 56, 58, 74, 60, 'Veggie hero saving the supermarket!', '/deckImages/kidstv/supertato.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Sportacus', 78, 59, 74, 55, 69, 'Leaping into action with healthy energy.', '/deckImages/kidstv/sportacus.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'The Clangers', 34, 46, 40, 85, 75, 'Whistling aliens on a tiny blue planet.', '/deckImages/kidstv/clangers.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Cookie Monster', 72, 39, 49, 96, 57, 'C is for cookie – and chaotic fun.', '/deckImages/kidstv/cookie_monster.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Shaun the Sheep', 55, 58, 53, 86, 70, 'A silent schemer with woolly antics.', '/deckImages/kidstv/shaun.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Ben and Holly', 42, 67, 45, 80, 68, 'Magic, royalty, and fairy mischief.', '/deckImages/kidstv/ben_holly.jpg'),
((SELECT id FROM decks WHERE name = 'Kids-tv'), 'Mister Maker', 37, 83, 40, 79, 72, 'Art and crafts faster than you can blink.', '/deckImages/kidstv/mister_maker.jpg');
