-- Seed file for Stat Attack database
-- This file seeds four decks and associated cards to the decks and cards tables
-- Decks included are: The Simpsons (35 cards), Harry Potter(30 cards), Marvel(30 cards), Disney(30 cards)
-- Run this after all migrations are complete

-- Clear existing data
DELETE FROM cards;
DELETE FROM decks;

-- Reset ID sequences
ALTER SEQUENCE decks_id_seq RESTART WITH 1;
ALTER SEQUENCE cards_id_seq RESTART WITH 1;

-- Insert decks
INSERT INTO decks (name, unique_stat_name, thumbnail)
VALUES
('The Simpsons', 'D''oh! Factor', '/deckImages/simpsons/thumbnail.jpg'),
('Harry Potter', 'Spellcasting', '/deckImages/harryPotter/thumbnail.jpg'),
('Marvel', 'Superpower', '/deckImages/marvel/thumbnail.jpg'),
('Disney', 'Disney Magic', '/deckImages/disney/thumbnail.jpg');

-- Insert cards
INSERT INTO cards
(deck_id, name, strength, wisdom, defence, unique_stat, luck, flavour_text, image)
VALUES
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Homer Simpson', 65, 30, 50, 95, 40, 'Loves donuts. Frequently causes his own disasters.', '/deckImages/simpsons/homer.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Marge Simpson', 50, 70, 65, 20, 60, 'The patient glue holding the family together.', '/deckImages/simpsons/marge.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Bart Simpson', 40, 45, 35, 80, 75, 'Eat my shorts!', '/deckImages/simpsons/bart.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Lisa Simpson', 30, 95, 40, 10, 70, 'A saxophone-playing genius in a world of chaos.', '/deckImages/simpsons/lisa.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Maggie Simpson', 10, 80, 20, 5, 85, 'Silent, but somehow still saves the day.', '/deckImages/simpsons/maggie.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Ned Flanders', 45, 75, 60, 5, 65, 'Hi-diddly-ho, neighborino!', '/deckImages/simpsons/ned.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Mr. Burns', 20, 85, 25, 50, 15, 'Excellent... but weak.', '/deckImages/simpsons/burns.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Waylon Smithers', 35, 75, 45, 15, 40, 'Burns’ loyal assistant. Has all his shots.', '/deckImages/simpsons/smithers.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Milhouse Van Houten', 25, 50, 30, 60, 35, 'Everything’s coming up Milhouse!', '/deckImages/simpsons/milhouse.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Nelson Muntz', 65, 35, 55, 70, 30, 'Ha-ha!', '/deckImages/simpsons/nelson.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Ralph Wiggum', 15, 20, 20, 99, 90, 'I choo-choo-choose chaos.', '/deckImages/simpsons/ralph.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Chief Wiggum', 50, 35, 45, 75, 50, 'The law is optional.', '/deckImages/simpsons/wiggum.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Apu Nahasapeemapetilon', 45, 85, 40, 30, 70, 'Thank you, come again!', '/deckImages/simpsons/apu.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Comic Book Guy', 25, 90, 35, 40, 25, 'Worst. Stat block. Ever.', '/deckImages/simpsons/comic_book_guy.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Moe Szyslak', 55, 40, 55, 60, 45, 'Owner of the saddest bar in town.', '/deckImages/simpsons/moe.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Barney Gumble', 70, 20, 50, 90, 30, 'Burp-powered powerhouse.', '/deckImages/simpsons/barney.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Krusty the Clown', 30, 50, 35, 85, 65, 'Funny, in a depressing kind of way.', '/deckImages/simpsons/krusty.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Sideshow Bob', 40, 95, 50, 20, 45, 'Revenge is an art form.', '/deckImages/simpsons/sideshow_bob.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Principal Skinner', 40, 75, 55, 25, 50, 'Steamed hams specialist.', '/deckImages/simpsons/skinny.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Edna Krabappel', 30, 80, 45, 35, 55, 'Don’t test her patience.', '/deckImages/simpsons/edna.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Groundskeeper Willie', 80, 50, 75, 45, 35, 'Angry, shirtless, and proud.', '/deckImages/simpsons/willie.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Lenny Leonard', 45, 50, 40, 60, 50, 'Carl’s other half.', '/deckImages/simpsons/lenny.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Carl Carlson', 50, 55, 45, 55, 55, 'The voice of reason at the plant.', '/deckImages/simpsons/carl.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Itchy', 90, 30, 35, 85, 50, 'Tiny, violent mouse.', '/deckImages/simpsons/itchy.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Scratchy', 85, 25, 30, 95, 45, 'Unlucky cartoon cat.', '/deckImages/simpsons/scratchy.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Patty Bouvier', 35, 65, 40, 20, 30, 'Chain-smoking cynic.', '/deckImages/simpsons/patty.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Selma Bouvier', 35, 60, 40, 25, 30, 'Also a chain-smoking cynic.', '/deckImages/simpsons/selma.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Reverend Lovejoy', 30, 70, 45, 10, 50, 'Spiritually checked out.', '/deckImages/simpsons/lovejoy.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Snake Jailbird', 60, 40, 45, 75, 35, 'Yesss, crime is cool.', '/deckImages/simpsons/snake.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Dr. Nick Riviera', 25, 30, 20, 88, 25, 'Hi everybody!', '/deckImages/simpsons/dr_nick.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Kent Brockman', 30, 75, 30, 20, 40, 'I, for one, welcome our new insect overlords.', '/deckImages/simpsons/kent.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Troy McClure', 40, 55, 30, 65, 50, 'You might remember him from such cards as this one.', '/deckImages/simpsons/troy.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Hans Moleman', 5, 40, 10, 99, 15, 'Moleman in the Morning is canceled.', '/deckImages/simpsons/moleman.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Bumblebee Man', 35, 30, 35, 80, 55, '¡Ay, caramba!', '/deckImages/simpsons/bumblebee.jpg'),
((SELECT id FROM decks WHERE name = 'The Simpsons'), 'Fat Tony', 65, 60, 55, 35, 40, 'The godfather of Springfield crime.', '/deckImages/simpsons/fat_tony.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Harry Potter', 75, 70, 65, 90, 80, 'The Boy Who Lived. And Lived. And Lived.', '/deckImages/harryPotter/harry.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Hermione Granger', 40, 99, 55, 95, 60, 'Probably read this card before you did.', '/deckImages/harryPotter/hermione.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Ron Weasley', 60, 65, 60, 70, 75, 'Loyal sidekick. Accident-prone, charmingly so.', '/deckImages/harryPotter/ron.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Albus Dumbledore', 40, 99, 85, 99, 70, 'More titles than a fantasy novel.', '/deckImages/harryPotter/dumbledore.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Lord Voldemort', 85, 90, 75, 98, 20, 'He Who Must Not Be Underestimated.', '/deckImages/harryPotter/voldemort.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Severus Snape', 50, 95, 70, 92, 45, 'Always.', '/deckImages/harryPotter/snape.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Draco Malfoy', 45, 60, 40, 65, 50, 'Talks big. Often runs away.', '/deckImages/harryPotter/draco.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Minerva McGonagall', 55, 90, 85, 95, 50, 'Strict, brilliant, occasionally turns into a cat.', '/deckImages/harryPotter/mcgonagall.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Rubeus Hagrid', 90, 45, 70, 35, 65, 'Larger than life. And magical creatures.', '/deckImages/harryPotter/hagrid.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Sirius Black', 70, 70, 65, 80, 60, 'Loyal, brave, tragically misunderstood.', '/deckImages/harryPotter/sirius.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Remus Lupin', 65, 85, 70, 85, 55, 'Werewolf with wisdom and a heart.', '/deckImages/harryPotter/lupin.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Bellatrix Lestrange', 70, 75, 60, 95, 40, 'Mad, bad, and magically dangerous.', '/deckImages/harryPotter/bellatrix.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Luna Lovegood', 35, 80, 45, 75, 90, 'Exceptionally odd, exceptionally gifted.', '/deckImages/harryPotter/luna.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Neville Longbottom', 60, 70, 80, 70, 65, 'The unlikeliest hero. Until he isn’t.', '/deckImages/harryPotter/neville.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Ginny Weasley', 65, 70, 60, 80, 70, 'Quiet strength, blazing Bat-Bogey Hexes.', '/deckImages/harryPotter/ginny.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Fred Weasley', 50, 65, 55, 60, 85, 'Half of a prank legend.', '/deckImages/harryPotter/fred.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'George Weasley', 50, 65, 55, 60, 85, 'Other half of a prank legend.', '/deckImages/harryPotter/george.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Molly Weasley', 65, 75, 70, 70, 55, 'Do not cross this mum.', '/deckImages/harryPotter/molly.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Arthur Weasley', 40, 70, 60, 65, 60, 'Fascinated by Muggle plugs.', '/deckImages/harryPotter/arthur.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Fleur Delacour', 60, 75, 60, 75, 70, 'Beauxbatons’ best, with Veela flair.', '/deckImages/harryPotter/fleur.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Cedric Diggory', 70, 75, 70, 70, 65, 'The goodest boy in Hogwarts.', '/deckImages/harryPotter/cedric.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Cho Chang', 45, 70, 50, 65, 70, 'Seeker of hearts and snitches.', '/deckImages/harryPotter/cho.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Lucius Malfoy', 55, 80, 60, 72, 40, 'Fancy cane, shady morals.', '/deckImages/harryPotter/lucius.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Nymphadora Tonks', 55, 75, 60, 75, 80, 'Don’t call her Nymphadora.', '/deckImages/harryPotter/tonks.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Kingsley Shacklebolt', 65, 85, 75, 85, 60, 'Cool under pressure. And with spells.', '/deckImages/harryPotter/kingsley.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Dolores Umbridge', 20, 70, 45, 60, 20, 'Pink, perky, and pure evil.', '/deckImages/harryPotter/umbridge.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Horace Slughorn', 40, 80, 55, 70, 65, 'Knows everyone, and their potions.', '/deckImages/harryPotter/slughorn.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Gilderoy Lockhart', 20, 60, 30, 25, 90, 'Author, fraud, legend in his own mind.', '/deckImages/harryPotter/lockhart.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Alastor Moody', 80, 70, 90, 85, 45, 'Constant vigilance!', '/deckImages/harryPotter/moody.jpg'),
((SELECT id FROM decks WHERE name = 'Harry Potter'), 'Peter Pettigrew', 30, 50, 40, 55, 25, 'Wormtail: rat in every sense.', '/deckImages/harryPotter/pettigrew.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Spider-Man', 60, 85, 50, 95, 70, 'Agile web-slinger with a sixth sense for danger.', '/deckImages/marvel/spiderman.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Iron Man', 70, 95, 60, 85, 50, 'Genius inventor in a high-tech suit of armor.', '/deckImages/marvel/ironman.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Thor', 95, 80, 90, 100, 60, 'God of Thunder wielding Mjolnir.', '/deckImages/marvel/thor.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Hulk', 95, 45, 85, 85, 35, 'The madder he gets, the stronger he gets.', '/deckImages/marvel/hulk.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Captain America', 85, 70, 80, 60, 75, 'Super soldier with an indestructible shield.', '/deckImages/marvel/captainamerica.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Black Widow', 65, 80, 70, 50, 85, 'Master spy and hand-to-hand combatant.', '/deckImages/marvel/blackwidow.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Doctor Strange', 50, 100, 60, 95, 40, 'Sorcerer Supreme with mystical abilities.', '/deckImages/marvel/doctorstrange.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Black Panther', 90, 85, 85, 75, 65, 'King of Wakanda with enhanced abilities.', '/deckImages/marvel/blackpanther.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Ant-Man', 50, 75, 60, 65, 80, 'Can shrink to the size of an ant with increased strength.', '/deckImages/marvel/antman.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Wolverine', 95, 60, 85, 90, 55, 'Regenerative healing factor and adamantium claws.', '/deckImages/marvel/wolverine.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Scarlet Witch', 70, 95, 75, 100, 65, 'Reality-warping powers and chaos magic.', '/deckImages/marvel/scarletwitch.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Vision', 85, 90, 80, 80, 60, 'Android with the Mind Stone and density control.', '/deckImages/marvel/vision.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Falcon', 75, 70, 65, 60, 85, 'Skilled pilot and hand-to-hand combatant.', '/deckImages/marvel/falcon.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Hawkeye', 70, 80, 65, 55, 90, 'Master archer with impeccable aim.', '/deckImages/marvel/hawkeye.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Star-Lord', 65, 75, 70, 60, 80, 'Leader of the Guardians with a quick wit.', '/deckImages/marvel/starlord.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Gamora', 85, 70, 75, 65, 75, 'Deadliest woman in the universe.', '/deckImages/marvel/gamora.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Drax', 95, 50, 90, 80, 50, 'Driven by vengeance and unmatched strength.', '/deckImages/marvel/drax.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Rocket Raccoon', 60, 80, 55, 70, 85, 'Weapons expert with a sharp tongue.', '/deckImages/marvel/rocketraccoon.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Groot', 100, 40, 95, 85, 60, 'Tree-like being with regenerative abilities.', '/deckImages/marvel/groot.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Deadpool', 85, 70, 60, 90, 95, 'Regenerative healing and a twisted sense of humor.', '/deckImages/marvel/deadpool.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Thanos', 100, 85, 90, 100, 50, 'Mad Titan with the power of the Infinity Stones.', '/deckImages/marvel/thanos.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Loki', 70, 90, 65, 85, 75, 'God of Mischief with illusionary powers.', '/deckImages/marvel/loki.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Venom', 90, 80, 75, 90, 65, 'Alien symbiote with enhanced strength.', '/deckImages/marvel/venom.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Magneto', 80, 95, 70, 100, 60, 'Master of magnetism and metal manipulation.', '/deckImages/marvel/magneto.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Storm', 75, 90, 70, 95, 65, 'Weather-controlling mutant with flight capabilities.', '/deckImages/marvel/storm.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Rogue', 85, 75, 80, 90, 70, 'Absorbs powers and memories through touch.', '/deckImages/marvel/rogue.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Professor X', 70, 100, 60, 95, 50, 'Telepathic leader of the X-Men.', '/deckImages/marvel/professorx.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Jean Grey', 80, 95, 70, 90, 60, 'Telekinetic and telepathic mutant.', '/deckImages/marvel/jeangrey.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Cyclops', 85, 80, 75, 85, 65, 'Optic blast-wielding leader of the X-Men.', '/deckImages/marvel/cyclops.jpg'),
((SELECT id FROM decks WHERE name = 'Marvel'), 'Silver Surfer', 80, 90, 80, 100, 55, 'Cosmic-powered herald who soars the spaceways on his board.', '/deckImages/marvel/silversurfer.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Mickey Mouse', 40, 80, 40, 95, 85, 'The face of Disney — cheerful, clever, and full of wonder.', '/deckImages/disney/mickey.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Minnie Mouse', 35, 75, 45, 85, 90, 'Graceful, loving, and always in style.', '/deckImages/disney/minnie.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Donald Duck', 50, 65, 50, 60, 70, 'Short temper, big heart, and even bigger voice.', '/deckImages/disney/donald.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Goofy', 60, 55, 60, 50, 95, 'Clumsy, lucky, and full of surprises.', '/deckImages/disney/goofy.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Elsa', 70, 80, 75, 99, 60, 'Queen of ice and empowerment.', '/deckImages/disney/elsa.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Anna', 60, 70, 65, 75, 85, 'Brave, loyal, and full of warmth.', '/deckImages/disney/anna.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Olaf', 35, 60, 40, 70, 99, 'Loves warm hugs and summer.', '/deckImages/disney/olaf.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Simba', 80, 70, 75, 65, 70, 'King in the making with a mighty roar.', '/deckImages/disney/simba.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Mufasa', 90, 85, 90, 80, 60, 'The wise and noble king of the Pride Lands.', '/deckImages/disney/mufasa.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Scar', 65, 85, 55, 75, 40, 'Cunning, theatrical, and full of betrayal.', '/deckImages/disney/scar.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Ariel', 50, 70, 60, 90, 75, 'Curious mermaid with a voice of magic.', '/deckImages/disney/ariel.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Ursula', 60, 80, 65, 95, 50, 'Sea witch with serious flair.', '/deckImages/disney/ursula.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Aladdin', 70, 75, 65, 85, 80, 'Street-smart prince with a magic carpet.', '/deckImages/disney/aladdin.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Genie', 80, 85, 70, 99, 70, 'Phenomenal cosmic powers, itty-bitty living space.', '/deckImages/disney/genie.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Jasmine', 60, 80, 60, 75, 85, 'Royal rebel with a strong will.', '/deckImages/disney/jasmine.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Moana', 80, 75, 75, 80, 70, 'Wayfinder, ocean whisperer, and heart of Te Fiti.', '/deckImages/disney/moana.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Maui', 95, 60, 80, 85, 55, 'Demigod of the wind and sea. You’re welcome.', '/deckImages/disney/maui.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Tiana', 70, 85, 70, 70, 65, 'Hard-working dreamer turned princess.', '/deckImages/disney/tiana.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Rapunzel', 55, 85, 60, 90, 80, 'Hair for days. Hope for miles.', '/deckImages/disney/rapunzel.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Flynn Rider', 65, 70, 60, 60, 85, 'Smolder level: expert.', '/deckImages/disney/flynn.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Cinderella', 40, 75, 50, 85, 95, 'Proof that shoes can change your life.', '/deckImages/disney/cinderella.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Belle', 45, 90, 55, 80, 75, 'Brains, books, and beauty.', '/deckImages/disney/belle.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Beast', 90, 70, 85, 70, 65, 'Big and brooding, with a tender heart.', '/deckImages/disney/beast.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Maleficent', 70, 90, 75, 98, 55, 'Mistress of all evil, and it shows.', '/deckImages/disney/maleficent.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Peter Pan', 55, 70, 55, 80, 95, 'Never grows up — also flies.', '/deckImages/disney/peterpan.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Tinker Bell', 35, 65, 40, 85, 90, 'Small, sparkly, and sassy.', '/deckImages/disney/tinkerbell.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Hercules', 95, 60, 85, 75, 70, 'Zero to hero real quick.', '/deckImages/disney/hercules.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Stitch', 85, 50, 75, 70, 85, 'Cute and chaotic. Mostly chaotic.', '/deckImages/disney/stitch.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Pocahontas', 70, 80, 70, 75, 80, 'Speaks to nature. Runs like the wind.', '/deckImages/disney/pocahontas.jpg'),
((SELECT id FROM decks WHERE name = 'Disney'), 'Mulan', 85, 85, 80, 70, 75, 'Saved China. Disguised as a man. NBD.', '/deckImages/disney/mulan.jpg');


