name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: stat_attack_development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/stat_attack_development
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      ISSUER: ${{ secrets.AUTH0_ISSUER_URI }}

    strategy:
      matrix:
        maven: [ 3.9.6 ]

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          distribution: 'temurin'
          maven-version: ${{ matrix.maven }}

      - name: Build and test with Maven
        run: mvn clean install

      - name: Upload Surefire test reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
